### ISSUE TITLE
[FEATURE & SUMMARY] InventoryCleaner "Re-Code" information base

### ISSUE THREAD

**Issue by derech1e** [CCBlueX/LiquidBounce1.8-Issues#3928]
In this article I would like to briefly summarize all problems and Feature-suggestions. This issue is intended to simplify, push and conclude the recode forward. If I have time, I will create a PR from my record, as a base on which the work can continue. The article also contains some suggestion from me.

**Here is the current pinned Issue to this topic: #3604**

### Bugs:
- [ ] InventoryCleaner and Autoarmor get stuck (#3909)
It seems that InventoryCleaner and Autoarmor sometimes do not work in sync together, when you have a full inventory. I think this has to be checked again and also a test scenario has to be found.

- [ ] ChestStealer taking uslees stuff (#3602)

### Features: 

- [x] Aquar bypass (#3705)

- [ ] SimulateDrag (#3211)
This make not really sense for me, but it is maybe a funny visualization.

- [ ] Clean option (#3141)
Simply add an option to prevent the cleaning of the Inventory.

- [ ] Black- and Whitelist (#1393)
An option to switch between black- and whitelists. You should be able to customize these list. A default list is maybe good.

- [ ] Priority Order
With this feature you can select an order, in wich the Cleaner should work. For example:
1. Swap Sword (good for fight); then swap the hotbar; then drop the trash
2. Drop the trash; sort the inventory
...
You know what I mean. So this feature should also implemented in Cheaststealer and Autoarmor. So that the Module takes first the best sword and then the armor, or in a other sequence. I think it is should be customisable.

**Comment by Teals53** [comment]
add count for buckets or blocks

**Comment by derech1e** [comment]
> add count for buckets or blocks

Please write full sentences for a better understanding.

**Comment by Teals53** [comment]
just look at recode issue i write same thing here too

**Comment by CzechHek** [comment]
> ### Features: 
> - Aquar bypass (#3705)
> I think this Anticheat is to small and not used by that much Servers to bypass it.

Already sorted out https://github.com/CCBlueX/LiquidBounce/pull/132

**Comment by superblaubeere27** [comment]
👍

**Comment by derech1e** [comment]
> > ### Features:
> > 
> > * Aquar bypass (#3705)
> >   I think this Anticheat is to small and not used by that much Servers to bypass it.
> 
> Already sorted out [CCBlueX/LiquidBounce#132](https://github.com/CCBlueX/LiquidBounce/pull/132)

Ah okay, I didnt noticed it. Thanks
